#!/usr/bin/env python3
from __future__ import annotations
import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

REQUIRED = {"schema_version","record_id","record_type","actor","project_id","created_at","input_state_version","summary","payload"}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def record_files(repo: Path):
    root = repo / "researchops/outbox"
    return sorted(root.glob("*/*.json")) if root.exists() else []


def validate_record(rec: dict, path: Path, project_id: str) -> None:
    missing = REQUIRED.difference(rec)
    if missing:
        raise ValueError(f"{path}: missing fields {sorted(missing)}")
    if rec["project_id"] != project_id:
        raise ValueError(f"{path}: project_id mismatch")
    if rec["actor"] not in {"gpt","codex","human","system"}:
        raise ValueError(f"{path}: unsupported actor {rec['actor']!r}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Reduce append-only ResearchOps records into ordered state/ledger")
    ap.add_argument("--repo-root", required=True)
    args = ap.parse_args()
    repo = Path(args.repo_root).resolve()
    cfg = load_json(repo / "researchops/config.json")
    state_path = repo / "researchops/state/STATE.json"
    state = load_json(state_path)
    project_id = cfg["project_id"]
    processed = dict(state.get("processed_records") or {})
    new = []
    seen_ids = set(processed)
    for path in record_files(repo):
        rec = load_json(path)
        validate_record(rec, path, project_id)
        rid = rec["record_id"]
        if rid in seen_ids:
            continue
        seen_ids.add(rid)
        new.append((rec.get("created_at") or "", rid, path, rec))
    new.sort(key=lambda x: (x[0], x[1]))
    ledger_path = repo / "researchops/ledger/LEDGER.json"
    ledger = load_json(ledger_path)
    entries = list(ledger.get("entries") or [])
    last_seq = int(state.get("last_seq", 0))
    tasks = dict(state.get("tasks") or {})
    latest_by_actor = dict(state.get("latest_record_by_actor") or {})
    for _, rid, path, rec in new:
        last_seq += 1
        processed[rid] = last_seq
        latest_by_actor[rec["actor"]] = rid
        entries.append({"seq":last_seq,"record_id":rid,"record_type":rec["record_type"],"actor":rec["actor"],"created_at":rec["created_at"],"task_id":rec.get("task_id"),"summary":rec.get("summary", ""),"path":str(path.relative_to(repo)).replace("\\", "/")})
        rtype = rec["record_type"]
        task_id = rec.get("task_id")
        payload = rec.get("payload") or {}
        if rtype == "task" and task_id:
            idem = payload.get("idempotency_key")
            if idem:
                for existing_id, existing in tasks.items():
                    if existing_id != task_id and existing.get("idempotency_key") == idem and existing.get("status") in {"RUNNING","PASS"}:
                        raise ValueError(f"duplicate live/completed idempotency_key {idem!r}: {existing_id}, {task_id}")
            tasks[task_id] = {"status":"PENDING","task_record_id":rid,"authorization_level":payload.get("authorization_level"),"idempotency_key":idem,"input_state_version":rec.get("input_state_version"),"latest_result_id":None}
        elif rtype in {"result","event"} and task_id:
            task = tasks.setdefault(task_id, {"status":"UNKNOWN","task_record_id":None})
            status = payload.get("status")
            if status:
                task["status"] = status
            if rtype == "result":
                task["latest_result_id"] = rid
                state["latest_result_id"] = rid
        elif rtype == "decision":
            state["latest_decision_id"] = rid
        elif rtype == "approval":
            state["latest_approval_id"] = rid
    if new:
        state["state_version"] = int(state.get("state_version", 0)) + 1
        state["last_seq"] = last_seq
        state["updated_at"] = utc_now()
        state["processed_records"] = processed
        state["latest_record_by_actor"] = latest_by_actor
        state["tasks"] = tasks
        ledger["entries"] = entries
        state_path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        ledger_path.write_text(json.dumps(ledger, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        md = [f"# {project_id} ResearchOps Ledger","","Generated by the reducer. Do not edit manually.","","| Seq | Time | Actor | Type | Task | Record | Summary |","|---:|---|---|---|---|---|---|"]
        for e in entries:
            md.append(f"| S{e['seq']:06d} | {e['created_at']} | {e['actor']} | {e['record_type']} | {e.get('task_id') or '-'} | {e['record_id']} | {str(e['summary']).replace('|','/')} |")
        (repo / "researchops/ledger/LEDGER.md").write_text("\n".join(md) + "\n", encoding="utf-8")
        index_rel = cfg.get("researchops_sidecar_index_path") if cfg.get("index_mode") == "sidecar" else cfg["index_path"]
        idx = repo / index_rel
        lines = [f"# {project_id} ResearchOps Index","","Generated by the ResearchOps reducer. Do not edit manually.","",f"- Project slug: `{cfg['project_slug']}`",f"- State version: `{state['state_version']}`",f"- Last sequence: `{state['last_seq']}`",f"- Updated UTC: `{state['updated_at']}`","","## Tasks","","| Task | Status | Authorization | Input state | Latest result |","|---|---|---|---:|---|"]
        for tid in sorted(tasks):
            t = tasks[tid]
            lines.append(f"| {tid} | {t.get('status','-')} | {t.get('authorization_level') or '-'} | {t.get('input_state_version', '-')} | {t.get('latest_result_id') or '-'} |")
        lines += ["","## Navigation","","- [STATE](../../researchops/state/STATE.json)","- [Ordered ledger](../../researchops/ledger/LEDGER.md)","- [Machine ledger](../../researchops/ledger/LEDGER.json)"]
        idx.parent.mkdir(parents=True, exist_ok=True)
        idx.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Processed {len(new)} new records; state_version={state.get('state_version')}; last_seq={state.get('last_seq')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
